spring.application.name=transfers-service
server.port=8082

inventory.base-url=http://localhost:8083

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=tarpuq
spring.rabbitmq.password=tarpuq123
